### ISSUE TITLE
conf: 🛠️ Ajouter les extensions nécessaires dans Coder

### ISSUE THREAD

**Issue by philippart-s** [devrel-workshop/101-AI-Enpoints#23]
Le VSCode de coder n'a pas certaines extensions utiles au développement, si c'est possible ce serait top que l'image de base ait ces extensions (liste mouvante) : 
 - [ ] https://open-vsx.org/extension/redhat/java

**Comment by titimoby** [comment]
dans le template Coder, il y a un module qui permet de lancer le code-server avec des extensions.
module "code-server" {
  source   = "registry.coder.com/modules/code-server/coder"
  version  = "1.0.18"
  agent_id = coder_agent.main.id
  extensions = [
    "ms-python.python",
    "redhat.java"
  ]
}

il faudra probablement ajouter le template lui même à ce repository pour avoir une pleine reproductibilité

**Comment by titimoby** [comment]
La PR#33 comporte déjà les extensions pour java et python.
@philippart-s  Est ce qu'il y en a d'autres déjà identifiées ?

**Comment by philippart-s** [comment]
nop, il faudra que tu regardes la PR pour Python j'ai des galères de reconnaissance de packages installés dans VSCode, je t'en dirai plus dans la PR dédiée.
