### ISSUE TITLE
conf: 🛠️ script post install  dans le workspace

### ISSUE THREAD

**Issue by philippart-s** [devrel-workshop/101-AI-Enpoints#24]
En attendant de pouvoir l'automatiser dans Coder (si c'est possible), avoir un script de post install que pourront lancer les parcipant·es.

L'objectif de ce script est de positionner des variables (tokens par exemple) ou encore de finir de configurer des outils (venv Python par exemple).

Le script sera sourcé dans un fichier `.env` (**⚠️ à ne pas mettre dans git ⚠️**), pour le créer il faudra créer un .env.example qui servira de base (clefs + documentation sur comment aller populer la clef).

Ensuite un script `_post-install.sh` se chargera de faire les actions nécessaires.

C'est ce script qui, idéalement, sera appelé en automatique à la création du workspace.

A regarder côté VSCode mais il est possible de positionner l'exécution d'un script au moment d'afficher un terminal, à voir si cela peut palier Coder pour le post install.

**Comment by titimoby** [comment]
les templates Coder permettent de lancer un script une fois les ressources prêtes.
la mécanique du worjsop 101-AI-and-py doit pouvoir se retranscrire ici

**Comment by philippart-s** [comment]
La PR #25 est un début manuel d'initialisation avec un dot file et un script bash.
Je pense que l'on peut s'en servir comme base et voir ce que l'on rajoute dans coder ou pas si ça te le fait 😉
