### ISSUE TITLE
conf: 🛠️ Add NodeJS 20.x à Coder

### ISSUE THREAD

**Issue by philippart-s** [devrel-workshop/101-AI-Enpoints#29]
Pour utliser JS ajouter NodeJS 20.x (+ NPM en CLI)

**Comment by titimoby** [comment]
node 20 dans l'image mais pas vérifié encore si npm est bien présent

**Comment by philippart-s** [comment]
si il y a node il y a NPM normalement

**Comment by titimoby** [comment]
c'est vérifié et poussé dans la PR #33
